#ifndef WATCHY_FONT_WATCHYDIGITS4X7_H
#define WATCHY_FONT_WATCHYDIGITS4X7_H

// Auto-generated by /tmp/gen_watchy_font.py from
// src/faces/stats_glyphs.h hand-authored glyphs.
// Adafruit GFXfont format: bits packed MSB-first, row-major,
// continuous (no per-row padding).

#include <stdint.h>
#include <Arduino.h>   // PROGMEM
#include <gfxfont.h>

const uint8_t WatchyDigits4x7_Bitmaps[] PROGMEM = {
    0x80, 0x69, 0x99, 0x99, 0x60, 0xd5, 0x54, 0x69, 0x12, 0x48, 0xf0, 0x69,
    0x16, 0x19, 0x60, 0x11, 0x95, 0x29, 0x7c, 0x40, 0xf8, 0x8f, 0x11, 0xf0,
    0x69, 0x8e, 0x99, 0x60, 0xf1, 0x12, 0x44, 0x40, 0x69, 0x96, 0x99, 0x60,
    0x69, 0x97, 0x19, 0x60,
};

const GFXglyph WatchyDigits4x7_Glyphs[] PROGMEM = {
    {    0,   1,   1,   3,   1,    0 }, // '.' (0x2e)
    {    1,   0,   0,   0,   0,    0 }, // '/' (0x2f)
    {    1,   4,   7,   6,   0,   -6 }, // '0' (0x30)
    {    5,   2,   7,   4,   0,   -6 }, // '1' (0x31)
    {    7,   4,   7,   6,   0,   -6 }, // '2' (0x32)
    {   11,   4,   7,   6,   0,   -6 }, // '3' (0x33)
    {   15,   5,   7,   7,   0,   -6 }, // '4' (0x34)
    {   20,   4,   7,   6,   0,   -6 }, // '5' (0x35)
    {   24,   4,   7,   6,   0,   -6 }, // '6' (0x36)
    {   28,   4,   7,   6,   0,   -6 }, // '7' (0x37)
    {   32,   4,   7,   6,   0,   -6 }, // '8' (0x38)
    {   36,   4,   7,   6,   0,   -6 }, // '9' (0x39)
};

const GFXfont WatchyDigits4x7 PROGMEM = {
    (uint8_t  *)WatchyDigits4x7_Bitmaps,
    (GFXglyph *)WatchyDigits4x7_Glyphs,
    0x2e, 0x39, 8
};

#endif // WATCHY_FONT_WATCHYDIGITS4X7_H
