#ifndef WATCHY_FONT_WATCHYDIGITS5X7_H
#define WATCHY_FONT_WATCHYDIGITS5X7_H

// Auto-generated by /tmp/gen_watchy_font.py from
// src/faces/stats_glyphs.h hand-authored glyphs.
// Adafruit GFXfont format: bits packed MSB-first, row-major,
// continuous (no per-row padding).

#include <stdint.h>
#include <gfxfont.h>

const uint8_t WatchyDigits5x7_Bitmaps[] PROGMEM = {
    0x74, 0xeb, 0x5c, 0xc5, 0xc0, 0x23, 0x08, 0x42, 0x11, 0xc0, 0x74, 0x42,
    0x22, 0x23, 0xe0, 0xf0, 0x42, 0xe0, 0x87, 0xc0, 0x11, 0x95, 0x2f, 0x88,
    0x40, 0xfc, 0x21, 0xe0, 0x87, 0xc0, 0x32, 0x21, 0xe8, 0xc5, 0xc0, 0xf8,
    0x44, 0x22, 0x11, 0x00, 0x74, 0x62, 0xe8, 0xc5, 0xc0, 0x74, 0x62, 0xf0,
    0xc5, 0xc0,
};

const GFXglyph WatchyDigits5x7_Glyphs[] PROGMEM = {
    {    0,   5,   7,   6,   0,   -6 }, // '0' (0x30)
    {    5,   5,   7,   6,   0,   -6 }, // '1' (0x31)
    {   10,   5,   7,   6,   0,   -6 }, // '2' (0x32)
    {   15,   5,   7,   6,   0,   -6 }, // '3' (0x33)
    {   20,   5,   7,   6,   0,   -6 }, // '4' (0x34)
    {   25,   5,   7,   6,   0,   -6 }, // '5' (0x35)
    {   30,   5,   7,   6,   0,   -6 }, // '6' (0x36)
    {   35,   5,   7,   6,   0,   -6 }, // '7' (0x37)
    {   40,   5,   7,   6,   0,   -6 }, // '8' (0x38)
    {   45,   5,   7,   6,   0,   -6 }, // '9' (0x39)
};

const GFXfont WatchyDigits5x7 PROGMEM = {
    (uint8_t  *)WatchyDigits5x7_Bitmaps,
    (GFXglyph *)WatchyDigits5x7_Glyphs,
    0x30, 0x39, 8
};

#endif // WATCHY_FONT_WATCHYDIGITS5X7_H
