// Auto-generated by tools/gen_hourly_minute_map.py — do not edit.
// 60-entry minute -> (x,y) lookup for the HOURLY dial. Each entry is
// face-relative; minute 0 sits at top-center, indices advance clockwise.
#ifndef WATCHY_SCREENS_HOURLY_MINUTE_MAP_H
#define WATCHY_SCREENS_HOURLY_MINUTE_MAP_H

#include <stdint.h>

static constexpr int16_t kMinuteDot[60][2] = {
    {  91,  11 },  // minute 0
    {  99,  11 },  // minute 1
    { 107,  11 },  // minute 2
    { 115,  11 },  // minute 3
    { 123,  11 },  // minute 4
    { 131,  11 },  // minute 5
    { 139,  11 },  // minute 6
    { 148,  13 },  // minute 7
    { 153,  18 },  // minute 8
    { 157,  22 },  // minute 9
    { 162,  27 },  // minute 10
    { 164,  40 },  // minute 11
    { 164,  48 },  // minute 12
    { 164,  56 },  // minute 13
    { 164,  64 },  // minute 14
    { 164,  72 },  // minute 15
    { 164,  80 },  // minute 16
    { 164,  88 },  // minute 17
    { 164,  96 },  // minute 18
    { 162, 108 },  // minute 19
    { 157, 113 },  // minute 20
    { 153, 117 },  // minute 21
    { 148, 122 },  // minute 22
    { 139, 124 },  // minute 23
    { 131, 124 },  // minute 24
    { 123, 124 },  // minute 25
    { 115, 124 },  // minute 26
    { 107, 124 },  // minute 27
    {  99, 124 },  // minute 28
    {  91, 124 },  // minute 29
    {  83, 124 },  // minute 30
    {  75, 124 },  // minute 31
    {  67, 124 },  // minute 32
    {  59, 124 },  // minute 33
    {  51, 124 },  // minute 34
    {  43, 124 },  // minute 35
    {  35, 124 },  // minute 36
    {  27, 122 },  // minute 37
    {  22, 117 },  // minute 38
    {  18, 113 },  // minute 39
    {  13, 108 },  // minute 40
    {  12,  96 },  // minute 41
    {  12,  88 },  // minute 42
    {  12,  80 },  // minute 43
    {  12,  72 },  // minute 44
    {  12,  64 },  // minute 45
    {  12,  56 },  // minute 46
    {  12,  48 },  // minute 47
    {  12,  40 },  // minute 48
    {  27,  13 },  // minute 49
    {  22,  18 },  // minute 50
    {  18,  22 },  // minute 51
    {  13,  27 },  // minute 52
    {  36,  11 },  // minute 53
    {  43,  11 },  // minute 54
    {  51,  11 },  // minute 55
    {  51,  11 },  // minute 56
    {  67,  11 },  // minute 57
    {  75,  11 },  // minute 58
    {  83,  11 },  // minute 59
};

#endif // WATCHY_SCREENS_HOURLY_MINUTE_MAP_H
