#!/usr/bin/env python3
"""Generate src/faces/hourly_glyphs.h with 17x32 BIG digits 0-9.

Each digit is a 17-col x 32-row packed bitmap, MSB-first, 3 bytes per row.
Stroke style: 4-px thick verticals/horizontals, all-caps consistent style.
"""

DST = "/home/q/1Projects/Watchy/watchy-screens/src/faces/hourly_glyphs.h"

# Each digit is a list of solid rectangles (row0..row1, col0..col1, inclusive).
# All using a consistent "block" style: 4-px-thick strokes, 17x32 size.
# "4" is drawn telegraph-style (crossbar at rows 18-21) to match the
# reference image's bitmap exactly.
DIGITS = {
    '0': [
        (0,  3, 0, 16),    # top bar
        (4, 27, 0,  3),    # left vertical
        (4, 27, 13, 16),   # right vertical
        (28, 31, 0, 16),   # bottom bar
    ],
    '1': [
        (0, 31, 13, 16),   # right vertical, full height
    ],
    '2': [
        (0,  3, 0, 16),    # top
        (4, 13, 13, 16),   # upper-right
        (14, 17, 0, 16),   # middle
        (18, 27, 0,  3),   # lower-left
        (28, 31, 0, 16),   # bottom
    ],
    '3': [
        (0,  3, 0, 16),    # top
        (4, 13, 13, 16),   # upper-right
        (14, 17, 0, 16),   # middle
        (18, 27, 13, 16),  # lower-right
        (28, 31, 0, 16),   # bottom
    ],
    '4': [
        (0, 21, 0,  3),    # left vertical (extended down to crossbar)
        (0, 31, 13, 16),   # right vertical (full height)
        (18, 21, 0, 16),   # crossbar (matches reference image)
    ],
    '5': [
        (0,  3, 0, 16),    # top
        (4, 13, 0,  3),    # upper-left
        (14, 17, 0, 16),   # middle
        (18, 27, 13, 16),  # lower-right
        (28, 31, 0, 16),   # bottom
    ],
    '6': [
        (0,  3, 0, 16),    # top
        (4, 27, 0,  3),    # left vertical (full middle-section)
        (14, 17, 0, 16),   # middle
        (18, 27, 13, 16),  # lower-right
        (28, 31, 0, 16),   # bottom
    ],
    '7': [
        (0,  3, 0, 16),    # top
        (4, 31, 13, 16),   # right vertical (full down)
    ],
    '8': [
        (0,  3, 0, 16),    # top
        (4, 27, 0,  3),    # left vertical (full middle-section)
        (4, 27, 13, 16),   # right vertical (full middle-section)
        (14, 17, 0, 16),   # middle
        (28, 31, 0, 16),   # bottom
    ],
    '9': [
        (0,  3, 0, 16),    # top
        (4, 13, 0,  3),    # upper-left
        (4, 27, 13, 16),   # right vertical (down to bottom bar)
        (14, 17, 0, 16),   # middle
        (28, 31, 0, 16),   # bottom
    ],
}

W, H = 17, 32

def build(segments):
    grid = [[0] * W for _ in range(H)]
    for r0, r1, c0, c1 in segments:
        for r in range(r0, r1 + 1):
            for c in range(c0, c1 + 1):
                grid[r][c] = 1
    # Pack to 3 bytes/row, MSB-first
    rows = []
    for row in grid:
        b = bytearray(3)
        for c in range(W):
            if row[c]:
                b[c // 8] |= 0x80 >> (c % 8)
        rows.append(bytes(b))
    return rows

def fmt_row(row):
    return ", ".join(f"0x{b:02X}" for b in row)

with open(DST, "w") as f:
    f.write("// Hand-authored 17x32 BIG digits for the HOURLY face,\n")
    f.write("// generated by tools/gen_hourly_glyphs.py.\n")
    f.write("// Style: 4-px-thick strokes; \"4\" matches the reference's\n")
    f.write("// telegraph crossbar at rows 18-21; other digits use\n")
    f.write("// standard 7-segment positions (top 0-3, mid 14-17, bot 28-31).\n")
    f.write("// Packed MSB-first, 3 bytes per 17-col row.\n")
    f.write("#ifndef WATCHY_SCREENS_HOURLY_GLYPHS_H\n")
    f.write("#define WATCHY_SCREENS_HOURLY_GLYPHS_H\n\n")
    f.write("#include <stdint.h>\n\n")
    f.write(f"static const int GLYPH_HRL_BIG_W = {W};\n")
    f.write(f"static const int GLYPH_HRL_BIG_H = {H};\n")
    f.write(f"static const int GLYPH_HRL_BIG_STRIDE = 3;\n\n")
    for d in "0123456789":
        rows = build(DIGITS[d])
        f.write(f"static const uint8_t GLYPH_HRL_BIG_{d}_ROWS[{H}][3] = {{\n")
        for row in rows:
            f.write(f"    {{ {fmt_row(row)} }},\n")
        f.write("};\n\n")
    f.write("#endif // WATCHY_SCREENS_HOURLY_GLYPHS_H\n")

print(f"wrote {DST}")
