#!/usr/bin/env python3
"""Generate the 60-entry minute -> (x,y) lookup for the HOURLY dial.

The 60 positions come straight from `tools/detect_hourly_squares.py`,
which scans `references/hourly.png` for the perpendicular tick strokes
on each straight edge and computes the centre of every visible
"square" cell. Chamfer minutes (no individual squares — those corners
use a decorative checker pattern) are placed evenly along the inset
chamfer diagonal.

Re-run after any change to the static reference or the detector.
"""

import os
import subprocess
import sys

DST = "/home/q/1Projects/Watchy/watchy-screens/src/faces/hourly_minute_map.h"
DETECTOR = os.path.join(os.path.dirname(__file__), "detect_hourly_squares.py")

# Per-minute hand-tuned overrides applied after detection. Use only
# when a minute needs to deviate from the geometric square centre — for
# instance to nudge it into a visible decorative element. Currently
# none — the detector's output aligns with every visible square.
OVERRIDES: dict[int, tuple[int, int]] = {
    # Detector lands minute 56 in the 4th square left of "60" (col 59),
    # but visually that reads too far right; shift one square further
    # left to col 51 (square 3) so it sits with more breathing room
    # away from the "60" cell.
    56: (51, 11),
}


def detect_centers():
    """Run the detector and parse its `SQUARE_CENTERS = [...]` block."""
    out = subprocess.check_output([sys.executable, DETECTOR],
                                  text=True)
    centers = []
    in_block = False
    for line in out.splitlines():
        if line.startswith("SQUARE_CENTERS"):
            in_block = True
            continue
        if in_block:
            if line.startswith("]"):
                break
            # parse: "    ( 91,  11),  # minute 0"
            stripped = line.strip()
            if stripped.startswith("("):
                xy = stripped.split("#")[0].strip().rstrip(",").strip("()")
                x, y = (int(p.strip()) for p in xy.split(","))
                centers.append((x, y))
    if len(centers) != 60:
        raise RuntimeError(f"detector returned {len(centers)} centres, expected 60")
    return centers


def main():
    centers = detect_centers()
    for m, pt in OVERRIDES.items():
        centers[m] = pt

    with open(DST, "w") as f:
        f.write("// Auto-generated by tools/gen_hourly_minute_map.py — do not edit.\n")
        f.write("// 60-entry minute -> (x,y) lookup for the HOURLY dial. Each entry is\n")
        f.write("// face-relative; minute 0 sits at top-center, indices advance clockwise.\n")
        f.write("#ifndef WATCHY_SCREENS_HOURLY_MINUTE_MAP_H\n")
        f.write("#define WATCHY_SCREENS_HOURLY_MINUTE_MAP_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write("static constexpr int16_t kMinuteDot[60][2] = {\n")
        for m, (x, y) in enumerate(centers):
            f.write(f"    {{ {x:3d}, {y:3d} }},  // minute {m}\n")
        f.write("};\n\n")
        f.write("#endif // WATCHY_SCREENS_HOURLY_MINUTE_MAP_H\n")
    print(f"wrote {DST}")
    for tm in (0, 6, 8, 25, 47, 56):
        print(f"  minute {tm:2d} -> {centers[tm]}")


if __name__ == "__main__":
    main()
